spring:
  application:
    name: Hypérion
  datasource:
    url: jdbc:postgresql://localhost:5432/hyperion
    username: postgres
    password: mdp
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      hibernate:
        ddl-auto: update